import { EcommerceProvider } from "@/context/EcommerceContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" min-h-screen bg-[#f2f6fb] md:bg-[#f2f6fb]  flex flex-col md:justify-between">
        <EcommerceProvider>
        {children}
        </EcommerceProvider>
      </body>
    </html>
  );
}
